### KAKAO Test
GET https://dapi.kakao.com/v2/search/blog?query=여행 HTTP/1.1
Authorization: KakaoAK 7c46861feae1b0f674877784391af0d1


### NAVER Test
GET https://openapi.naver.com/v1/search/blog.json?query=%EC%97%AC%ED%96%89&display=10&start=1 HTTP/1.1
X-Naver-Client-Id: plALAdWlLgXCnAvucsVH
X-Naver-Client-Secret: abG7OQ4c_g


### sort : "accuracy" , "recency"
### Search BLOG Test
GET http://localhost:8080/search/blog HTTP/1.1
Content-Type: application/json

{
    "searchWord": "여행",
    "sort": "recency",
    "size": 0,
    "page": 1
}


### Get Rank Test
GET http://localhost:8080/search/rank HTTP/1.1
	
