### KAKAO Test
GET https://dapi.kakao.com/v2/search/blog?query=집짓기 HTTP/1.1
Content-Type: application/json;charset=UTF-8
Authorization: KakaoAK 7c46861feae1b0f674877784391af0d1


### Just Test
GET http://localhost:8080/search/test HTTP/1.1



### Search BLOG Test
GET http://localhost:8080/search/blog HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "searchWork": "test"
}


