server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  apikey:
    kakao: 7c46861feae1b0f674877784391af0d1
    naver-id: plALAdWlLgXCnAvucsVH
    naver-secret: abG7OQ4c_g
  transfer:
    kakao: https://dapi.kakao.com
    naver: https://openapi.naver.com